stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y awscli s3cmd

    # Set up AWS credentials
    - echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY > ~/.aws/credentials
    - aws configure set default.region $AWS_DEFAULT_REGION

    # Sync files with S3 bucket using awscli
    - aws s3 sync ./path/to/local/files s3://your-s3-bucket-name

    # Alternatively, you can use s3cmd for synchronization
    # - s3cmd sync ./path/to/local/files s3://your-s3-bucket-name

  only:
    - master # You can change this to the branch you want to trigger the deployment
